### ISSUE TITLE
wd:TimePicker Binding  绑定不上值的问题

### ISSUE THREAD

**Issue by hanhanyh** [WPFDevelopersOrg/WPFDevelopers#109]
既不能绑定值，也不能获取值，版本1.1.0.2-preview9，targetFramework="net45"
` <wd:TimePicker Width="120" Name="TimePicker1"   SelectedTime="{Binding Time,UpdateSourceTrigger=PropertyChanged}"    />`

**Comment by yanjinhuagood** [comment]
可以设置绑定模式为 `TwoWay`
~~~C#
<wd:TimePicker Width="200" SelectedTime="{Binding Time, Mode=TwoWay}" />
~~~
