### ISSUE TITLE
请问我使用该项目的地图控件，为什么我自己注册了bing地图密钥还是显示无效呀

### ISSUE THREAD

**Issue by Waiwai-Zhang** [WPFDevelopersOrg/WPFDevelopers#16]
如题

**Comment by yanjinhuagood** [comment]
https://mp.weixin.qq.com/s?__biz=MzAwMzI4Nzc5Mg==&mid=2647484519&idx=1&sn=deff47fa93676381f0b4f4a4a1a87ba8&chksm=8304b7f8b4733eee71100e3c2de679aaad0a76c5a1c9ff06c4877331af7c293be85bcb1872be&scene=178&cur_album_id=1785824210196463617&rd2werd=1&key=3f7397d1f5cd79873d379f0ed4d5c1c9aece42eebdcb37d829500b8642f99d40d9fdfe6aa366cbfbc5339fc3d26842f4fe94ef8edc25f82355d3bfdba290a5d1b9e6679814aa4987668466074520e10072dce29b9937771be44457f28d8462e711a08c6741f5a0cdcb8e3ba705db3477498b42ddf14d98964bfe8d701b581d87&ascene=7&uin=MjE2NjYzMDc1&devicetype=Windows+10+x64&version=63080014&lang=zh_CN&exportkey=n_ChQIAhIQlFOwHhkxvO8V0LHflm%2FKRxLXAQIE97dBBAEAAAAAALYKLduL0s8AAAAOpnltbLcz9gKNyK89dVj0WL58bWV5Q7AoP%2B6a1PsopTzyySH3gywcF1%2BjEjZv76GDuO%2FCSgqW%2B4tT9wWDi7eDVsxKh1%2FXKk1hURJakJ%2BLoXpAxLbXK2lAC5GHAlrS%2Bj4VYLWa%2BphU1ljsGPlhQfNgcV%2BaI1Ooc0LD2cqvdn4I6ivO79g9qMgHWncuinvKoeCrNKm%2BbmBZN6zmgcXQBXJkK4ePyDyH3vrCt7ic%2F8vkQ0rVkqlgO5R73Z5XTfyEXzs%2B&acctmode=0&pass_ticket=PIcMXuI%2B1nYzAq%2F07DHi%2Be6tKm2iYKS9zvaz5m2orjHw2m1mwo25z%2FZWzymCm2kT&wx_header=0&fontgear=2

你看看这里如果还是不行加我QQ或者wechat

**Comment by Waiwai-Zhang** [comment]
出现这个的原因是因为将地图控件加载在数据模板中，由于数据模板的特殊性质导致密钥加载失败，若一定要放在数据模板中，可以将地图控件包装成一个用户控件再加载，就能正常工作
