### ISSUE TITLE
为什么地图控件的卫星图无法加载

### ISSUE THREAD

**Issue by Waiwai-Zhang** [WPFDevelopersOrg/WPFDevelopers#39]
你好，我在模仿该库的做法来使用微软的MapControl，该控件有一个Mode属性，设置成Road则可以正常显示，而设置成Aerial就无法正常加载，奇怪的是在xaml设计器中可以看到预览，但是运行后加载不出。
<m:Map x:Name="map" CredentialsProvider="xxxxx"
               Mode="Aerial" ZoomLevel="15" Center="32.0354, 118.8203">
</m:Map>

**Comment by yanjinhuagood** [comment]
首先感谢使用，由于我们使用的是bingmap的例子，所以也没有源码不确定为什么 Mode="Aerial" 无法加载。

**Comment by Facebook979** [comment]
I don't know your language please provide in English UK

**Comment by yanjinhuagood** [comment]
@Waiwai-Zhang 
1.删除Map中的Mode="Aerial"
2.修改`AMapTitleLayer.cs`此处的代码逻辑https://github.com/WPFDevelopersOrg/WPFDevelopers/blob/master/src/WPFDevelopers.Samples.Shared/ExampleViews/Map/AMapTitleLayer.cshttps://github.com/WPFDevelopersOrg/WPFDevelopers/blob/master/src/WPFDevelopers.Samples.Shared/ExampleViews/Map/AMapTitleLayer.cs
![1698b7d824339418fbc9d734a93f9af](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/23089734/2b7c4ec3-7917-4722-99f3-ed7bfe6e6e67)

~~~C#
http://wprd01.is.autonavi.com/appmaptile?x={0}&y={1}&z={2}&lang=zh_cn&size=1&scl=1&style=6
~~~

**Comment by yanjinhuagood** [comment]
https://mp.weixin.qq.com/s/4Q1rdURpLsAIWZf-mGUBuA @Waiwai-Zhang

**Comment by yanjinhuagood** [comment]
嗯
