### ISSUE TITLE
lineChart控件无法找到

### ISSUE THREAD

**Issue by ypeng-ming** [WPFDevelopersOrg/WPFDevelopers#47]
您好，我没有在控件库里找到linechart，能麻烦告知一下吗？谢谢

**Comment by yanjinhuagood** [comment]
非常抱歉，没提过此控件。

**Comment by ypeng-ming** [comment]
好的  因为我在readme里看到了 所以以为有。。。

**Comment by yanjinhuagood** [comment]
> 好的  因为我在readme里看到了 所以以为有。。。

这个是一个sample 希望对你有帮助 https://github.com/WPFDevelopersOrg/WPFDevelopers/blob/master/src/WPFDevelopers.Samples.Shared/ExampleViews/LineChartExample.xaml
