### ISSUE TITLE
NotifyIcon 更换黑白皮肤后菜单皮肤未更改

### ISSUE THREAD

**Issue by aixiao2u1mei** [WPFDevelopersOrg/WPFDevelopers#58]
Nuget包版本：WPFDevelopers -Version 1.1.0.2-preview
现象复现步骤：
- 1.默认创建Window设置NotifyIcon，右下角可以正常显示托盘。
- 2.这个时候点击托盘图标右键时会显示菜单。
- 3.当我切换为黑皮肤时再次点击托盘右键还是默认显示白皮肤。

**Comment by yanjinhuagood** [comment]
已修复，请下载最新版 [nuget预览包](https://www.nuget.org/packages/WPFDevelopers/1.1.0.2-preview1)

**Comment by aixiao2u1mei** [comment]
验证通过，谢谢
