### ISSUE TITLE
有没有类似安卓的RecyclerView 控件

### ISSUE THREAD

**Issue by schyjxy** [WPFDevelopersOrg/WPFDevelopers#70]
安卓上有一个RecyclerView 控件，以瀑布流的形式流畅加载各种大图片，资源占用也很低。VirtualizingPanel 原理上应该可以实现，但我看了一个wpf 的UI 库，好像都没有类似的控件可以实现这个需求。

**Comment by yanjinhuagood** [comment]
非常抱歉，暂时还没有瀑布流控件。

**Comment by schyjxy** [comment]
好的

**Comment by yanjinhuagood** [comment]
@schyjxy 你好，请看[链接](https://github.com/WPFDevelopersOrg/WPFDevelopers/commit/33534f2406a9e833ecca0353943c3b0d8ca120b6)。
