### ISSUE TITLE
TransformThumb repositions when resized

### ISSUE THREAD

**Issue by codedom-git** [WPFDevelopersOrg/WPFDevelopers#74]
If you rotate the rectangle by 45 degrees, for example, and then grab the lower left corner, and pull down, the upper side of the rectangle moves, something that shouldn't happen, an animated image is attached.

![problem](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/152982996/a95dd28f-9102-4c7e-a87d-3e83bd5850e0)

The correct behavior should be like a Word rectangle, as in the animated image:

![wordRect](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/152982996/eff0ff6d-c646-42af-b512-01ea37d41aeb)

**Comment by yanjinhuagood** [comment]
Thank you for your feedback. We are very sorry that we have not found a good solution at the moment.
This update does not allow the width and height to exceed the size of the canvas area.
