### ISSUE TITLE
截屏内存无限制上涨的问题

### ISSUE THREAD

**Issue by 862256261** [WPFDevelopersOrg/WPFDevelopers#77]
执行截屏后内存没有自动释放，请解决一下吧谢谢

**Comment by yanjinhuagood** [comment]
GC垃圾回收器会自动进行内存管理，并在需要时释放不再使用的对象。

**Comment by 862256261** [comment]
并没有回收啊，内存蹭蹭上涨

**Comment by 862256261** [comment]
![1704785832226](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/37432536/1c18caf8-78bb-42d4-90f5-8750ac2ad81e)
![1704785858207](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/37432536/02751dee-a4cb-4eac-8e40-1ab0b0236766)
![1704785880857](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/37432536/520968f4-7592-407e-bb7f-67d191cd5401)
这分别是初次打开程序的内存，截图完成第一次的内存，截图完成第二次的内存

**Comment by yanjinhuagood** [comment]
正在解决中。

**Comment by yanjinhuagood** [comment]
1. 请使用最新[Nuget](https://www.nuget.org/packages/WPFDevelopers/1.1.0.2-preview5)
2. [下载](https://github.com/WPFDevelopersOrg/WPFDevelopers/releases/tag/1.1.0.2-preview5)体验

**Comment by yanjinhuagood** [comment]
示例代码：
~~~C#
 private void ButtonExt_Click(object sender, RoutedEventArgs e)
 {
     var screenCaptureExt = new ScreenCaptureExt();
     screenCaptureExt.SnapCanceled += ScreenCaptureExt_SnapCanceled;
     screenCaptureExt.SnapCompleted += ScreenCaptureExt_SnapCompleted;
 }
 private void ScreenCaptureExt_SnapCompleted(System.Windows.Media.Imaging.BitmapSource bitmap)
 {
 }

 private void ScreenCaptureExt_SnapCanceled()
 {
     Message.Push($"{DateTime.Now} 取消截图",MessageBoxImage.Information);
 }
~~~

**Comment by yanjinhuagood** [comment]
https://github.com/WPFDevelopersOrg/WPFDevelopers/wiki/ScreenCapture
