### ISSUE TITLE
下载到本地编译提示相关错误 

### ISSUE THREAD

**Issue by GitClound** [WPFDevelopersOrg/WPFDevelopers#94]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	XLS0414	未找到类型“WPFDevelopers.Samples.ExampleViews.AnimationNavigationBar3DExample”。请确保不缺少程序集引用并且已生成所有引用的程序集。	WPFDevelopers.SamplesCode	E:\Study\git\WPF\WPFDevelopers\src\WPFDevelopers.Samples.Shared\ExampleViews\AnimationNavigationBar3DExample.xaml	2		
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	CS2001	未能找到源文件“E:\Study\git\WPF\WPFDevelopers\src\WPFDevelopers.Shared\Controls\Loading\LoadingExt.cs”。	WPFDevelopers.Net45x (net45)	E:\Study\git\WPF\WPFDevelopers\src\WPFDevelopers.Net45x\CSC	1	活动	

![image](https://github.com/WPFDevelopersOrg/WPFDevelopers/assets/52389829/bb7d39ad-24c6-42a8-9679-1bde667b12a1)

**Comment by yanjinhuagood** [comment]
已修复，下载master分支即可
